apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: {{ goldfield }}
  labels:
    name: nginx
    AppID: {{ AppID }}
    ProjectKey: {{ Projectkey }}
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
