apiVersion: v1
kind: pod
metadata:
  name: nginx
  namespace: {{ ns }}
  labels:
    name: nginx
    projectkey: {{ projectkey }}
    AppID: {{ AppID }}
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
