---
- name: Generate template
  hosts: localhost
  tasks:
  - name: namespace
    fail:
      msg: "Invalid namespace"
    when: namespace!="goldfield"
  - name: application id
    fail:
      msg: "Invalid applicationid"
    when: AppID!="T001"
  - name: Projectkey
    fail:
      msg: "Invalid projectkey"
    when: Projectkey!="PH"
  - name: Generate pod template
    template:
      src: deployment.yaml
      dest: ./deployment.yaml
